baseURL = "/"
languageCode = "sv-SE"
title = "Wedding by ia event"

staticDir = ["static", "assets"]

defaultContentLanguage = "sv"
defaultContentLanguageInSubdir = false

enableEmoji = true
enableRobotsTXT = true
disableAliases = true


[params]
  description = "..."
  disallowSearchEngines = false # set robots.txt to disallow everything
  googleFonts = [
    "Advent Pro",
    "Work Sans"
  ]
  cloudinaryBase = "https://res.cloudinary.com/adambrgmn/image/upload/"

# add redirects/headers
[outputs]
  home = ["HTML", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

