baseURL = "/"
languageCode = "sv-SE"
title = "Wedding by ia event"

staticDir = ["static", "assets"]

defaultContentLanguage = "sv"
defaultContentLanguageInSubdir = false

enableEmoji = true
enableRobotsTXT = true
disableAliases = true

googleAnalytics = "UA-146122952-1"

[params]
  title = "Wedding by ia event"
  description = "Wedding by ia event arrangerar bröllop runt om i Göteborg och längs med Västkusten, men tar sig an uppdrag i hela Sverige och även utomlands."
  disallowSearchEngines = false # set robots.txt to disallow everything
  googleFonts = [
    "Montserrat:700",
    "Work Sans:400,700",
    "Playfair Display:400i"
  ]
  polyfills = [
    "IntersectionObserver",
    "requestAnimationFrame",
    "HTMLPictureElement"
  ]
  cloudinaryBase = "https://res.cloudinary.com/adambrgmn/image/upload/"
  images = [
    "https://res.cloudinary.com/adambrgmn/image/upload/c_fill,h_630,w_1200/v1566382614/ia-event/social-cover.jpg"
  ]

[params.contact]
  phone = "076-336 19 88"
  mail = "wedding@iaevent.se"

[social]
  facebook = "weddingbyiaevent"
  instagram = "weddingbyiaevent"
  pinterest = "weddingbyiaevent"

# add redirects/headers
[outputs]
  home = ["HTML", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

