[build]
  command = "NODE_ENV=production yarn build:assets && yarn build:hugo && yarn build:functions"
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.55.6"
  API_BASE = "/.netlify/functions"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "NODE_ENV=production yarn build:assets && yarn build:hugo -D -b $DEPLOY_PRIME_URL && yarn build:functions"

[context.branch-deploy]
  command = "NODE_ENV=production yarn build:assets && yarn build:hugo -D -b $DEPLOY_PRIME_URL && yarn build:functions"
